### ISSUE TITLE
Wayland support

### ISSUE THREAD

**Issue by adelin-b** [AlfredoSequeida/hints#2]
Awesome project,

Currently not supporting wayland (kde plasma 6) it seems. 

Here is an issue to track it. 

hints --mode hint

(hints:220277): Wnck-WARNING **: 15:09:59.075: libwnck is designed to work in X11 only, no valid display found

(hints:220277): Wnck-WARNING **: 15:09:59.075: libwnck is designed to work in X11 only, no valid display found
Traceback (most recent call last):
  File "/home/adelinb/.local/bin/hints", line 8, in <module>
    sys.exit(main())
             ~~~~^^
  File "/home/adelinb/.local/share/pipx/venvs/hints/lib/python3.13/site-packages/hints/hints.py", line 198, in main
    hint_mode(config, mouse)
    ~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/adelinb/.local/share/pipx/venvs/hints/lib/python3.13/site-packages/hints/hints.py", line 75, in hint_mode
    current_backend = backends_map[backend](config)
  File "/home/adelinb/.local/share/pipx/venvs/hints/lib/python3.13/site-packages/hints/backends/atspi.py", line 22, in __init__
    super().__init__(*args, **kwargs)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/adelinb/.local/share/pipx/venvs/hints/lib/python3.13/site-packages/hints/backends/backend.py", line 25, in __init__
    self.active_window = self.get_active_window()
                         ~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/adelinb/.local/share/pipx/venvs/hints/lib/python3.13/site-packages/hints/backends/backend.py", line 53, in get_active_window
    return self.window_manager.get_active_window()
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/adelinb/.local/share/pipx/venvs/hints/lib/python3.13/site-packages/hints/window_manager.py", line 21, in get_active_window
    self.screen.force_update()
    ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'force_update'

**Comment by drkknigt** [comment]
@adelin-b 
![2024-12-30_20-10](https://github.com/user-attachments/assets/314cc742-e10f-449f-b814-4ba9533dbb42) 

It currently only supports X11

**Comment by AlfredoSequeida** [comment]
Thank you for opening this. There has definitely been a lot of demand for this, so I plan to work on that more.

**Comment by AlfredoSequeida** [comment]
https://github.com/user-attachments/assets/65a80221-2aab-47ac-a279-8ce4dd425d0b

Happy new years 🎆 everyone! Small update, here is a demo working on sway. I had to do a good bit of rewriting to support sway, but the good thing is that things are more generic now to hopefully support other compositors. 

- I spent yesterday figuring out what was and wasn't possible on Wayland. Long story short, there does not seem to be a universal way of getting window information (postion/size/application name/focus state) from waylandlib. This is by desing. So this means that information will have to come from the compositor (for every compositor). So for sway I am wrapping `swaymsg`. Other wms will have to support gathering that information so they can be supported as well. 

- The demo is pretty much fully functional with a few expextions:
  - I need a way to control the mouse as pynput(the lib I was using on x11) does not work in sway. I started using ydotool in an effort to use one tool to support both x11 and Wayland. But from my testing that's a little broken. The absolute position does not work. Relative positioning does work, but I would need to move the mouse to (0,0) first to make that work. However, I have noticed if I do this using the absolute position feature in ydotool and then try to move relatively, the position of the cursor is incorrect. If I move the cursor myself to (0,0) and then have ydotool move the cursor, things do work. So I'm guessing ydotool might not be cleaning up properly after an absolute move. I have seen issues about absolute positionig not working for ydotool on the project's github page, so it might not just be my system.
  - I also tried dotool and wrlctl. dotool seemed to have the same improper positioning problem and wrlctl does not have absolute positioning. Thinking about it now, if both ydotool and dotool have the same issue, it might be worth trying a different system. I tested this on Manjaro sway.
  - If anyone here has suggestions please let me know. I would like to avoid writing my own solution here as that would just be another thing to support. But I did take a look at python-uninput, which also had its own issues. As well as writing a Wayland specific solution using https://wayland.app/protocols/wlr-virtual-pointer-unstable-v1,  but that would limit the amount of compositors that could be used to those shown at the bottom of that page. 

- I also know I will have to replace Pillow's ImageGrab module that I'm using to take a screenshot and store the contents in memory for the OpenCV backend. I saw this which might be helpful: https://github.com/ponty/pyscreenshot. Otherwise, I will have to look for another solution.

**Comment by drkknigt** [comment]
@AlfredoSequeida How to build hints for sway branch .

**Comment by AlfredoSequeida** [comment]
@drkknigt you can either follow the instructions in the README for development or install it using pipx. 

`pipx install git+https://github.com/AlfredoSequeida/hints.git@wayland/sway`

Make sure to install the dependencies for your system like shown in the installation part of the README. 

Additionally for Sway you will need to install:

- gtk-layer-shell (https://github.com/wmww/gtk-layer-shell)
- jq (https://github.com/jqlang/jq)
- ydotool (https://github.com/ReimuNotMoe/ydotool)

And you will need to create a config file to tell hints to use the sway window system (see the wiki to see how to create a configuration file). Then in your config you need this option [here](https://github.com/AlfredoSequeida/hints/blob/e585109413cae7d4ca43b442a98e1daab9b6b7c9/hints/constants.py#L101). So for sway that will be "sway" instead of "x11". I need to find out how I can figure out the wm at runtime, so for now it's a config option.

**Comment by jheroy** [comment]
@AlfredoSequeida  I am using the Wayland/Sway branch on Hyprland and modified "window_system": "sway". It reports the following error:
```
Traceback (most recent call last):
  File "/home/xxx/github/hints/venv/bin/hints", line 5, in <module>
    from hints.hints import main
  File "/home/xxx/github/hints/hints/hints.py", line 11, in <module>
    from pynput.mouse import Button, Controller
  File "/home/xxx/github/hints/venv/lib/python3.13/site-packages/pynput/__init__.py", line 40, in <module>
    from . import keyboard
  File "/home/xxx/github/hints/venv/lib/python3.13/site-packages/pynput/keyboard/__init__.py", line 31, in <module>
    backend = backend(__name__)
  File "/home/xxx/github/hints/venv/lib/python3.13/site-packages/pynput/_util/__init__.py", line 77, in backend
    raise ImportError('this platform is not supported: {}'.format(
    ...<5 lines>...
            if resolutions else '')
ImportError: this platform is not supported: ('failed to acquire X connection: Bad display name ""', DisplayNameError(''))

Try one of the following resolutions:

 * Please make sure that you have an X server running, and that the DISPLAY environment variable is set correctly
```

**Comment by AlfredoSequeida** [comment]
I'm assuming you see this while typing hints? Or performing some. Of the mouse commands? I noted in the update above that is still not done. But I'm working on that now and made some progress.  I'll update the beanch with my progress later today. I'm really close to a fully functioning sway version.

**Comment by Xemptuous** [comment]
Adding wayland support is great, but it seems to only be applicable to sway, not wayland as a whole.

I'm running hyprland and I get the error:

```
FileNotFoundError: [Errno 2] No such file or directory: 'swaymsg'
```

Would be great to see hyprland support added as well.

**Comment by AlfredoSequeida** [comment]
@Xemptuous correct, this only works on sway for now. But part of the updates include making the code more generic to allow other compositors to be added.

**Comment by drkknigt** [comment]
@AlfredoSequeida how about using the value of SWAYSOCK to figure out if Sway is running or not? SWAYSOCK specifies the path to the Sway IPC socket, so if it's set, we can assume Sway is running.

**Comment by AlfredoSequeida** [comment]
@drkknigt Ah nice I didn't know about that thank you. I wonder if other wayland compositors have something similar. I'm trying to avoid parsing the process tree.

**Comment by AlfredoSequeida** [comment]
[recording_20250101-204736.webm](https://github.com/user-attachments/assets/a28b476e-06ae-4b08-bc2b-1dfb0ac52310)
Update, the mouse functionality is working now, and the read me has been update for how to get that to work for Sway.

**Comment by AlfredoSequeida** [comment]
Update, I added multi-monitor support functionality and removed the need to specify the window system in the config. I added a [function to parse the system processes](https://github.com/AlfredoSequeida/hints/blob/c33627cf87c4179b3a005f29a5a4590e92643ede/hints/hints.py#L247), which I have only tested on i3 (x11) and sway.  But hopefully that will also work for other wms. 

I feel this is in a good state, I just need to write some docs to document how to write window systems to support other window managers.

**Comment by AlfredoSequeida** [comment]
Hello everyone, Sway functionality has been merged into main, but this issue will remain open as the original issue asking for KDE Plasma 6 support has not been resolved.

**Comment by jheroy** [comment]
I tried replacing the implementation of Sway with Hyprland's commands and encountered two issues. One is that the hints menu pops up too slowly, taking at least one second. The other is that the labels of many applications do not match their actual content, which might be related to dark mode. It's possible that both issues are due to the use of OpenCV for content recognition? This solution was mentioned in this https://github.com/moverest/wl-kbptr/issues/9  before, but the actual performance might not be ideal.

**Comment by AlfredoSequeida** [comment]
@jheroy I started working on the hyperland implementation today. You can checkout the wayland/hyprland branch. It's already functioning.

And yes, OpenCV is likely to be less performant than the astpi backend. If the application you're testing supports the atspi backend, that would be best to use. For that you need to follow the instructions in the README to setup accessibility. If it doesn't,  then yes that's a limitation the more processing power you have the better.

And as for the dark mode point, there is a section in the wiki that shows you how to invert the colors to improve OpenCV accuracy.

**Comment by AlphaSoundZ** [comment]
```
(hints:525980): Gtk-WARNING **: 23:53:36.712: Negative content height -1 (allocation 1, extents 1x1) while allocating gadget (node border, owner GtkFrame)
c0 11
```

I get this error when running hints on Hyprland (Wayland).

**Comment by AlfredoSequeida** [comment]
> ```
> (hints:525980): Gtk-WARNING **: 23:53:36.712: Negative content height -1 (allocation 1, extents 1x1) while allocating gadget (node border, owner GtkFrame)
> c0 11
> ```
> 
> I get this error when running hints on Hyprland (Wayland).

@AlphaSoundZ This looks like a Warning, not an error. Does it affect how hints show up?

**Comment by AlphaSoundZ** [comment]
> > ```
> > (hints:525980): Gtk-WARNING **: 23:53:36.712: Negative content height -1 (allocation 1, extents 1x1) while allocating gadget (node border, owner GtkFrame)
> > c0 11
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I get this error when running hints on Hyprland (Wayland).
> 
> [@AlphaSoundZ](https://github.com/AlphaSoundZ) This looks like a Warning, not an error. Does it affect how hints show up?

Yes, the hints show up, but the cursor does not move where it should. 
But the cursor moves.

And another thing. hints does not handle my keyboard layout correctly.

I'm using DVORAK but it reads the default querty layout I assume.

**Comment by AlfredoSequeida** [comment]
> > > ```
> > > (hints:525980): Gtk-WARNING **: 23:53:36.712: Negative content height -1 (allocation 1, extents 1x1) while allocating gadget (node border, owner GtkFrame)
> > > c0 11
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > I get this error when running hints on Hyprland (Wayland).
> > 
> > 
> > [@AlphaSoundZ](https://github.com/AlphaSoundZ) This looks like a Warning, not an error. Does it affect how hints show up?
> 
> Yes, the hints show up, but the cursor does not move where it should. But the cursor moves.
> 
> And another thing. hints does not handle my keyboard layout correctly.
> 
> I'm using DVORAK but it reads the default querty layout I assume.

For the mouse you need to disable mouse acceleration for the ydotool virtual device if you have not already. There's instructions for that in the wiki: https://github.com/AlfredoSequeida/hints/wiki/Window-Manager-and-Desktop-Environment-Setup-Guide#hyprland

For the keyboard layout, there are instructions in the wiki for using different layouts: https://github.com/AlfredoSequeida/hints/wiki/Configuration-guide#alphabet

**Comment by AlfredoSequeida** [comment]
834e0c0d013ec6eb6b2a179243a9711c3824ea69 Adds Plasma 6 support, hints work, but I have noticed that absolute ydotool mouse movements consistently move the mouse to 0,0. There is an issue in the ydotool repo that mentions this, but this is the first wayland compositor that I have experience the issue in. I know [kdotool](https://github.com/jinliu/kdotool) exists for plasma, so that could be an alternative for plasma.

**Comment by mayushii21** [comment]
@AlfredoSequeida when will Plasma support be merged into main, is this planned? The [wayland/plasmashell](https://github.com/AlfredoSequeida/hints/tree/wayland/plasmashell) branch is quite a bit behind main, and I can't find any docs on configuring hints for KDE

**Comment by AlfredoSequeida** [comment]
> @AlfredoSequeida when will Plasma support be merged into main, is this planned? The [wayland/plasmashell](https://github.com/AlfredoSequeida/hints/tree/wayland/plasmashell) branch is quite a bit behind main, and I can't find any docs on configuring hints for KDE

I haven't had too much time to work on it lately. The work needed is done. However mouse dragging is still not working. But from my investigation, this is not unique to plasma, this is the case for all Wayland. So with that in mind, this should probably be good to merge and the other mouse issues could be addressed in the future. I imagine most people probably don't need to drag anyways. If I have some time this weekend I'll rebase from main and merge it thr changes.

**Comment by mayushii21** [comment]
> I imagine most people probably don't need to drag anyways. If I have some time this weekend I'll rebase from main and merge the changes.

That would be much appreciated! I personally indeed do not need the drag feature and am just after the hints

**Comment by AlfredoSequeida** [comment]
Merged in #45
