### ISSUE TITLE
cannot run in second Xorg server? for Xnest DISPLAY=:1,  `active_window` is `None`

### ISSUE THREAD

**Issue by WillForan** [AlfredoSequeida/hints#6]
Trying to isolate hints in it's own xserver (to debug keyboard grabbing issues) but don't have much luck. Might be a GTK limitation?

```
Xnest :1 & sleep 1; DISPLAY=:1 xterm -e 'echo $DISPLAY; hints; read' 
```

```
:1

Traceback (most recent call last):
  File "/home/foranw/.local/bin/hints", line 8, in <module>
    sys.exit(main())
             ~~~~^^
  File "/home/foranw/.local/share/pipx/venvs/hints/lib/python3.13/site-packages/hints/hints.py", line 198, in main
    hint_mode(config, mouse)
    ~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/foranw/.local/share/pipx/venvs/hints/lib/python3.13/site-packages/hints/hints.py", line 75, in hint_mode
    current_backend = backends_map[backend](config)
  File "/home/foranw/.local/share/pipx/venvs/hints/lib/python3.13/site-packages/hints/backends/atspi.py", line 22, in __init__
    super().__init__(*args, **kwargs)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/foranw/.local/share/pipx/venvs/hints/lib/python3.13/site-packages/hints/backends/backend.py", line 26, in __init__
    self.window_extents = self.active_window.get_geometry()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_geometry'
```

**Comment by AlfredoSequeida** [comment]
Interesting, I'm not too familiar with Xnest nor have I tried running multiple display servers before, so I'm not too sure how to help there, but if I get a chance I'll try in on my end as well.

**Comment by AlfredoSequeida** [comment]
@WillForan So again, this is my first time using `Xnest` and I see the same error. After some investigation, I'm pretty sure this is due to the xsession not declaring the window as active, so you need to set the state of the window as active so that wnck can pick it up. From the [wnck docs:](https://lazka.github.io/pgi-docs/Wnck-3.0/classes/Screen.html#Wnck.Screen.get_active_window) 
```
Gets the active [Wnck.Window](https://lazka.github.io/pgi-docs/Wnck-3.0/classes/Window.html#Wnck.Window) on self. May return [None](https://docs.python.org/3/library/constants.html#None) sometimes, since not all window managers guarantee that a window is always active.
````

So this worked for me:

Start Xnest and a winidow manager (in this case icewm) in a one terminal:
```
Xnest :1 & sleep 1; DISPLAY=:1 icewm;
```

Start an application to draw hints for in another
```
DISPLAY=:1 firefox
```

Then draw hints in another terminal emulator window
```
DISPLAY=:1 hints
```

I don't get transparency for the hints window, but this is just because I don't have compositing setup in icewm.

**Comment by AlfredoSequeida** [comment]
Closing assuming the solution provided works as expected.
